### ISSUE TITLE
Find people for vacant positions 

### ISSUE THREAD

**Issue by mahadi117** [AIRS-ORG/Committee-Tasks#2]
Supreme Leader: Ideal (Social Media Manager)/ Meem 
- [ ] Put the description of the vacant positions in the social media 
- [ ] Send out emails 
- [x] Advertisement them on website and in meetings

**Comment by Nnadozie** [comment]
Mahadi I think we should make it clear that only members can apply for these positions. Can I go ahead and include that in the emails and the posts on social media.

**Comment by mahadi117** [comment]
Yes you can!

**Comment by mahadi117** [comment]
This are specifications for the roles: (draft version)
supreme leaders:
President:
1.  Lead discussions about tasks which need to be done,
2.  Ensuring QMSU rules are there.
3.  Organise meeting,
4.  Delegate tasks,
5.  Handle recruitment,
6.  Provide vision and leadership and make decisions
7.  Makes executive decisions for the society

Designer:
Tasks:
1.  Design posters.
2.  Website layouts.
3.  Design adverts for different events which will be used in fb posts and stuff, leaflets etc.

Treasurer: 
Tasks: 
1.  Know the current financial status.
2.  making sure people hand in receipts for their expenses
3.  Filing these expense claims
4.  Prepare budget for the semesters, 
5.  Apply for funding/get funding
6.  Make sure events are within budget (give regular updates of finances)
7.  Check up on su coordinator for buying equipment (order equipment in good time)
8.  Authorisation of leaflets and posters by SU.

Social secretary  

Task:
1.  Posting updates in social media.
2.  responding to social media messages
3.  Taking pictures and recording events
4.  Handling advertising of society, such as putting up posters.

**Comment by Nnadozie** [comment]
Please reach an agreement with Rob asap so I can do this.

Seeing as 
- Will is taking on the treasurer role, 
- Ryan the workshop role Patrick is doing, and
- Jamie the social sec, 

we only seem to need a **designer** and  the **tech /project manager role for advanced projects** by a masters or phd student.
As well as future volunteers to help out with events like organising a hackathon or a competitions but that's another issue.

**Comment by mahadi117** [comment]
We have sorted the matter out. And we are going to discuss it more in the welcome meeting today evening. We might need a designer and a project manager when we have set up the project.

**Comment by Nnadozie** [comment]
Alright. Just fill me in after the meeting on how you sorted it out. This task can be closed because I was supposed to do has been done by you guys,
