### ISSUE TITLE
Send out email to members about student data lab events.

### ISSUE THREAD

**Issue by mahadi117** [AIRS-ORG/Committee-Tasks#3]
Send out email about the information contained in this mail from Liam

> Hi,
> 
> I'm the Founder of Student Data Labs - data-driven Innovation Labs for university students to learn practical data skills whilst working on civic problems.
> 
> I'd like to ask if the Artificial Intelligence and Robotics Society would be interested in an event we're running in London?
> 
> The Empty Housing Innovation Lab will explore how to address long-term empty properties in the city using data science and open data. There will be a short Data Workshop - where participants will be able to learn practical data skills and hear talks - and an Innovation Lab.
> 
> Taking place on Saturday 29th October at the London campus of Liverpool Uni near the Barbican, it's being run in collaboration with Consumer Data Research Centre (CDRC). A link to the event can be found here.
> 
> It would also be fantastic to have you guys involved in some capacity.
> 
> I look forward to hearing from you.
> 
> Cheers,
> 
> Liam
> Founder of Student Data Labs
> W: studentdatalabs.com
> F: https://www.facebook.com/StudentDataLabs
> T: https://twitter.com/StudentDataLabs

**Comment by Nnadozie** [comment]
Sent info in today's email.
